from django.urls import path, include
from . import views

urlpatterns = [
    path ('admin-dashboard/', views.dashboard, name = "dashboard" ),
    path ('admin_base/', views.admin_base, name = 'admin_base'),
    path('newsletter-signup/', views.newsletter_signup, name='newsletter_signup'),
    path('viewers/', views.viewers_details, name='viewers_details'),
    path ('internship_enquiries/', views.internship_applications, name = 'internship_enquiries'),
    path('intern_update_status/<int:candidate_id>/<str:new_status>/', views.update_internship_status, name='update_internship_status'),
    path('internship-application/delete/<int:application_id>/', views.delete_internship_application, name='delete_internship_application'),
    path ('job_applications/', views.job_applications, name = 'job_applications'),
    path ('ip_address/', views.ip_address, name = 'ip_address'),
    path ('newsletter/', views.newsletter, name = 'newsletter'),
    path('edit_newsletter/<int:newsletter_id>/', views.edit_newsletter, name='edit_newsletter'),
    path('unsubscribe/<str:email>/', views.unsubscribe, name='unsubscribe'),
    path('newsletter_subscribers_report/', views.newsletter_subscribers_report, name='newsletter_subscribers_report'),
    path ('product_launch/', views.product_launchs, name = 'product_launch'),
    path('edit_product_launch/<int:product_launch_id>/', views.produch_launch_edit, name='produch_launch_edit'),
    path ('send-notification/', views.send_notifications, name='send_notifications'),  
    path('save-email-template/', views.save_email_template, name='save_email_template'),
    path('email-template-form/', views.email_template_view, name='email_template_form'),


    
    path('report_admin/', views.report, name='report_admin'),
    path ('job_report/', views.job_report, name='job_report'),
    path ('contactus_report/', views.contactus_report, name='contactus_report'),
    path ('newsletter_subscribers_report',views.newsletter_subscribers_report,name="newsletter_subscribers_report"),
    path ('internship_report/', views.internship_report, name='internship_report'),


    path ('pinenews/', views.pinenews, name = 'pinenews'),
    path ('push_notifications/', views.push_notifications, name = 'push_notifications'),
    path ('current_user/', views.current_user, name = 'current_user'),
    path ('top_cities/', views.top_cities, name = 'top_cities'),
    path ('google_analytics/', views.google_analytics, name = 'google_analytics'),
    path ('heatmap/', views.heatmap, name = 'heatmap'),
    path ('report_generation/', views.report_generation, name = 'report_generation'),
    path ('blog/', views.blog, name = 'blog'), 
    path ('email_notifications/', views.admin_base, name = 'admin_base'),
    path ('culture/', views.culture, name = 'culture'),
    path ('client/', views.manage_client_pages, name = 'client'),
    path('edit-client-page/<int:id>/', views.edit_client_page, name='edit_client_page'),
    path('client/delete/', views.delete_client_page, name='delete_client_page'),  # New delete URL
    path('jobpost_view', views.job_post_list_create, name='job_post_list_create'),
    path('jobpost_delete/<int:pk>/', views.job_post_delete, name='job_post_delete'),
    path('jobpost_edit/<int:pk>/', views.job_post_edit, name='job_post_edit'),
    path('update_status/<int:candidate_id>/<str:new_status>/<str:email>/<str:name>/', views.update_status, name='update_status'),
    path('delete_candidate/<int:candidate_id>/', views.delete_candidate, name='delete_candidate'),


    path ('portfolio_post/', views.portfolio_post, name = "portfolio_post"),
    path('portfolios/edit/<int:pk>/', views.portfolio_edit, name='edit_portfolio'),
    path('portfolio/delete/<int:pk>/', views.delete_portfolio, name='delete_portfolio'),
    path('save-location/', views.save_location, name='save_location'),
    path('delete_pageview/<int:pk>/', views.delete_pageview, name='delete_pageview'),
    path('enquiries/', views.enquiry_list, name='enquiry_list'),
    path('enquiry/delete/<int:enquiry_id>/', views.delete_enquiry, name='delete_enquiry'),
    path ('save_fcm_token/', views.save_fcm_token, name= 'fcm'),
    path('submit-internship-application/', views.save_internship_application, name='submit_internship_application'),
    path('delete_application/<int:pk>/', views.delete_application, name='delete_application'),
    path('apply/',views.apply, name= 'apply'),
    path('device_info/', views.get_device_info, name= 'device_info'),
    path('view-resume/<int:application_id>/', views.view_resume, name='view_resume'),
    path('life_at_pine_post/', views.life_at_pinesphere_create, name= 'life_at_pine_post'),
    path('life-at-pinesphere/edit/<int:pk>/', views.edit_life_at_pinesphere, name='edit_life_at_pinesphere'),
    path('life-at-pinesphere/delete/<int:pk>/', views.delete_life_at_pinesphere, name='delete_life_at_pinesphere'),
    path('pinenews/edit/<int:pk>/', views.update_pine_news, name='edit_pinenews'),
    path('pinenews/delete/<int:pk>/', views.delete_pinenews, name='delete_pinenews'),
    path('pine_news/<int:pk>/image/', views.serve_image, name='serve_image'),
    path('apply/',views.apply, name= 'apply'),
    path('get_page_view_counts/',views.get_page_view_counts, name= 'get_page_view_counts'),
        path('get_device_type_counts/',views.get_device_type_counts, name= 'get_device_type_counts'),





    path('accounts/login/', views.login_view, name='login'),  # Add this line
    path('logout/', views.logout_view, name='logout'),
    path('billing/', views.billing, name='billing'),
    path('rtl/', views.rtl, name='rtl'),
    path('tables/', views.tables, name='tables'),
    path('profile/', views.profile, name='profile'),
    path('signup/', views.signup, name='signup'),



    path('',views.index,name='index'), 
    path('about_us/', views.about_us, name = "about_us"),
    path('base/',views.base,name='base'),
    path('lifeatpines/', views.lifeatpines, name = "lifeatpines"),
    path('careers/', views.careers, name = "careers"),
    path('digital_learning/',views.digital_learning,name='digital_learning'), 
    path('Ml_Ai/',views.Ml_Ai,name='Ml_Ai'), 
    path('iotservice/', views.IotService, name = "iotservice"),
    path('dwmservice/', views.DwmService, name = "dwmservice"),
    path('rpaservice/', views.RpaService, name = "rpaservice"),
    path('cloudservice/', views.CloudService, name = "cloudservice"),
    path('portfolio/', views.portfolio, name = "portfolio"),
    path('workwithus/', views.workwithus, name = "workwithus"),
    path('t_c/', views.t_c, name = "t_c"),
    path('privacy_p/', views.privacy_p, name = "privacy_p"),
    path('support/', views.support, name = "support"),
    path('ContactUs/', views.ContactUs, name = "ContactUs"),
    path('teams/', views.teams, name = "teams"),
    path('Pines_News_R/', views.Pines_News_R, name = "Pines_News_R"),
    path('form/<int:job_id>/', views.form, name = "form"),
    path('pinesnews1/', views.pinesnews1, name = "pinesnews1"),
    path('pinesnews2/', views.pinesnews2, name = "pinesnews2"),
    path('pinesnews3/', views.pinesnews3, name = "pinesnews3"),
    path('sustainability/', views.sustainability , name = "sustainability "),
       path('recognition/', views.recognition , name = "recognition"),
       path('ourbrand/', views.ourbrand, name = "ourbrand"),
       path('customer/', views.customer, name = "customer"),
       path('investors/', views.investors, name = "investors"),
       path('whypine/', views.whypine, name = "whypine"),
       path('capabilities/', views.capabilities, name = "capabilities"),
       path('industries/', views.industries, name = "industries"),
       path('Industries_services/', views.Industries_services, name = "Industries_services"),
       path('case_studies/', views.case_studies, name = "case_studies"),
       path('analyst_insights/', views.analyst_insights, name = "analyst_insights"),
       path('View/', views.View, name = "View"),
       path('corporate/', views.corporate, name = "corporate"),
       path('pineway/', views.pineway, name = "pineway"),
       path('insights/', views.insights, name = "insights"),
       path('Foundation/', views.Foundation, name = "Foundation"),
       path('social_responsibility/', views.social_responsibility, name = "social_responsibility"),
       path('education/', views.education, name = "education"),

]