# Generated by Django 5.1.1 on 2024-10-14 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_dashboard', '0003_internshipapplication_alter_pageview_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internshipapplication',
            options={},
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='timestamp',
            field=models.DateField(auto_now=True),
        ),
    ]
