# Generated by Django 5.1.1 on 2024-10-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_dashboard', '0004_alter_internshipapplication_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageview',
            name='user_agent',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
