# Generated by Django 5.1.1 on 2024-10-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_dashboard', '0005_pageview_user_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageview',
            name='user_browser',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
