# Generated by Django 5.1.1 on 2024-10-14 08:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_dashboard', '0006_pageview_user_browser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageview',
            name='user_unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
