# Generated by Django 5.1.1 on 2024-10-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_dashboard', '0007_alter_pageview_user_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipapplication',
            name='resume',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
