# Generated by Django 5.1.1 on 2024-10-15 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_dashboard', '0008_alter_internshipapplication_resume'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PineNewsCategories',
        ),
        migrations.RemoveField(
            model_name='pinenewsimage',
            name='pine_news',
        ),
        migrations.DeleteModel(
            name='PineNewsTags',
        ),
        migrations.DeleteModel(
            name='PineNewsImage',
        ),
    ]
