# Generated by Django 5.1.1 on 2024-10-15 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_dashboard', '0009_delete_pinenewscategories_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pinenews',
            options={},
        ),
    ]
