# Generated by Django 5.1.1 on 2024-10-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_dashboard', '0010_alter_pinenews_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinenews',
            name='image',
            field=models.BinaryField(default=None),
            preserve_default=False,
        ),
    ]
