# Generated by Django 5.1.1 on 2024-10-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_dashboard', '0012_alter_pinenews_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinenews',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/'),
        ),
    ]
