# Generated by Django 5.1.1 on 2024-10-16 09:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_dashboard', '0013_alter_pinenews_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='life_at_pinesphere',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
