# Generated by Django 5.1.1 on 2024-10-17 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_dashboard', '0015_jobformsubmission_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobformsubmission',
            name='submitted_at',
        ),
    ]
