# Generated by Django 5.1.1 on 2024-10-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_dashboard', '0016_remove_jobformsubmission_submitted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobformsubmission',
            name='job_id',
            field=models.CharField(max_length=200),
        ),
    ]
