# Generated by Django 5.1.1 on 2024-10-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_dashboard', '0017_alter_jobformsubmission_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobformsubmission',
            name='willing_to_relocate',
            field=models.CharField(max_length=50),
        ),
    ]
