# Generated by Django 5.1.1 on 2024-10-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_dashboard', '0019_internshipapplication_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('publish_date', models.DateField()),
                ('url', models.URLField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='assets/Images/pine_images/')),
                ('subtopic1_heading', models.CharField(max_length=255)),
                ('subtopic1_content', models.TextField()),
                ('subtopic1_url', models.URLField(max_length=500)),
                ('subtopic1_image', models.ImageField(blank=True, null=True, upload_to='assets/Images/pine_images/')),
                ('subtopic2_heading', models.CharField(max_length=255)),
                ('subtopic2_content', models.TextField()),
                ('subtopic2_url', models.URLField(max_length=500)),
                ('subtopic2_image', models.ImageField(blank=True, null=True, upload_to='assets/Images/pine_images/')),
            ],
        ),
    ]
