# Generated by Django 5.1.1 on 2024-10-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_dashboard', '0020_newsletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='publish_date',
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/assets/Images/pine_images/'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='subtopic1_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/assets/Images/pine_images/'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='subtopic2_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/assets/Images/pine_images/'),
        ),
    ]
