# Generated by Django 5.1.1 on 2024-10-18 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_dashboard', '0021_remove_newsletter_publish_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='contact_mail',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsletter',
            name='contact_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
