# Generated by Django 5.1.1 on 2024-10-18 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_dashboard', '0022_newsletter_contact_mail_newsletter_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='contact_number',
            field=models.BigIntegerField(),
        ),
    ]
