# Generated by Django 5.1.1 on 2024-10-18 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_dashboard', '0023_alter_newsletter_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='static/assets/Images/pine_images/'),
        ),
    ]
