# Generated by Django 5.1.1 on 2024-10-18 17:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_dashboard', '0024_newsletter_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_launch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='static/assets/Images/pine_images/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('url', models.URLField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/assets/Images/pine_images/')),
                ('contact_number', models.BigIntegerField()),
                ('contact_mail', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
