# Generated by Django 5.1.1 on 2024-10-18 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_dashboard', '0025_product_launch_internshipapplication_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_launch',
            name='contact_mail',
        ),
        migrations.RemoveField(
            model_name='product_launch',
            name='contact_number',
        ),
    ]
