# Generated by Django 5.1.1 on 2024-10-19 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_dashboard', '0026_remove_product_launch_contact_mail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email_Template_JI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Subject', models.CharField(max_length=255)),
                ('content', models.TimeField()),
                ('footer', models.TextField()),
            ],
        ),
    ]
