# Generated by Django 5.1.1 on 2024-10-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_dashboard', '0027_email_template_ji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_template_ji',
            name='content',
            field=models.TextField(),
        ),
    ]
